
global:
  scrape_interval: 5s

# if you want to get some insights about physical node, you can install node_exporter from prometheus.io
# I will add this later to my Dockerfile
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
